### ISSUE TITLE
PLAN - v1.2.0

### ISSUE THREAD

**Issue by dhodvogner** [dhodvogner/clean-my-workspace#1]
# v1.2.0 Plans

## Fix plans

- [ ] UI: Add "Abandoned" label under % circles
- [ ] UI: Project card web components
- [ ] UI: Format dates: "ago.."
- [ ] UI: Display dates nicer
- [ ] UI: Enable users to change directories -> call `/explore` than fetch `/results`
- [x] API: move out all the express stuff into `src/api` #2 
- [x] API: create new `/explore` POST route from `getResults()` #2 
- [x] Main: Remove the `Where is your Workplace folder?` question use CWD as default #2 
- [ ] Main: Imrpvoe ora's management and logging in general
- [ ] Style: eslint + StandardJS

## Flexible plans

- Check npmjs for version numbers, print out a notification if there is a new release
- Analyse folders based on file types like Github (N% Javascript; N% Html etc.)
